### ISSUE TITLE
ARM64 architecture

### ISSUE THREAD

**Issue by francescor** [logocomune/webhookdocker#6]
Hi there!
Thanks for your work!

I would like to request a release of the image for the ARM64 architecture. Currently, only the x86_64 version is available, and having an ARM64 option would be incredibly helpful for us to we can move to cheaper ARM-based systems. 

Thank you for considering this!

**Comment by logocomune** [comment]
Hi there!

Thank you for your message and for the kind words!

I've gone ahead and created a new image compatible with ARM64. I ran some quick tests, and it seems to be working well. However, I would greatly appreciate any feedback you might have.

The updated multi-architecture image for linux/amd64 and linux/arm64 is available here: 

**logocomune/webhook-docker:1.3.1-multi-arch**.

Looking forward to hearing your thoughts!

**Comment by francescor** [comment]
Yes
```
docker manifest inspect logocomune/webhook-docker:1.3.1-multi-arch | grep -i arch 
            "architecture": "amd64",
            "architecture": "arm64",
            "architecture": "unknown",
            "architecture": "unknown",
```
and it works (we have it in production now with aws `t4g` arm instances)

thank you!
